### ISSUE TITLE
Your TEAPIKEY is public?

### ISSUE THREAD

**Issue by mmurasawa** [mkol5222/tpapi_cli#1]
I found your TEAPIKEY in code...
I did not try this key, but if this code available now, you have trouble.

please check your code 

https://github.com/mkol5222/tpapi_cli/blob/84ebb88d738e58af82af514766d1850e3209beec/download_report.sh#L4

**Comment by mkol5222** [comment]
Thanks for notification. This is API key is expired and is one of time limited keys for 30 days, so it is OK that it remains in source code for demonstration purposes. However your note about keys and credentials in public sourcecode is correct and valid.

**Comment by mmurasawa** [comment]
OK.

I'm relieved to hear that.

Thanks.
